---
abstract: 'retrieve data from Nike+ public interface'
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Nike-NikePlus-Public
provides:
  WWW::Nike::NikePlus::Public:
    file: lib/WWW/Nike/NikePlus/Public.pm
    version: 0.01
recommends:
  Test::Perl::Critic: 0
  Test::Prereq::Build: 0
requires:
  Carp: 0
  Class::Accessor: 0
  English: 0
  Env: 0
  File::Slurp: 0
  Module::Build: 0.30
  Params::Validate: 0
  Test::Exception: 0
  Test::MockObject::Extends: 0
  Test::More: 0
  WWW::Mechanize: 0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/NIKEPUB#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/NIKEPUB
  ProjectWiki: http://logiclab.jira.com/wiki/display/NIKEPUB/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-Nike-NikePlus-Public
  homepage: http://logiclab.jira.com/wiki/display/NIKEPUB/Home
  license: http://dev.perl.org/licenses/
  repository: http://logicLAB.jira.com/svn/NIKEPUB
version: 0.01
